spring:
  h2:
    console:
      enabled: true

  datasource:
    url: 'jdbc:h2:mem:testdb'
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 6484bad6b0521f31f7fca78c30752386
            client-secret: KXpCbKAGWDXsWsBs5BeNTv4NGsvn9FMQ
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.security: DEBUG

